module.exports = [
  { fullName: "EUR - €", currencyCode: "EUR", currencySymbol: "€" },
  { fullName: "GBP - £", currencyCode: "GBP", currencySymbol: "£" },
  { fullName: "USD - $", currencyCode: "USD", currencySymbol: "$" },
  { fullName: "AED - AED", currencyCode: "AED", currencySymbol: "AED" },
  { fullName: "AFN - AFN", currencyCode: "AFN", currencySymbol: "AFN" },
  { fullName: "ALL - Lek", currencyCode: "ALL", currencySymbol: "Lek" },
  { fullName: "AMD - դր.", currencyCode: "AMD", currencySymbol: "դր." },
  { fullName: "ANG - NAf.", currencyCode: "ANG", currencySymbol: "NAf." },
  { fullName: "AOA - Kz", currencyCode: "AOA", currencySymbol: "Kz" },
  { fullName: "ARS - $", currencyCode: "ARS", currencySymbol: "$" },
  { fullName: "AUD - $", currencyCode: "AUD", currencySymbol: "$" },
  { fullName: "AWG - Afl.", currencyCode: "AWG", currencySymbol: "Afl." },
  { fullName: "AZN - ₼", currencyCode: "AZN", currencySymbol: "₼" },
  { fullName: "BAM - КМ", currencyCode: "BAM", currencySymbol: "КМ" },
  { fullName: "BBD - $", currencyCode: "BBD", currencySymbol: "$" },
  { fullName: "BDT - BDT", currencyCode: "BDT", currencySymbol: "BDT" },
  { fullName: "BGN - лв.", currencyCode: "BGN", currencySymbol: "лв." },
  {
    fullName: "BHD - د.ب.‏",
    currencyCode: "BHD",
    currencySymbol: "د.ب.‏",
  },
  { fullName: "BIF - FBu", currencyCode: "BIF", currencySymbol: "FBu" },
  { fullName: "BMD - $", currencyCode: "BMD", currencySymbol: "$" },
  { fullName: "BND - $", currencyCode: "BND", currencySymbol: "$" },
  { fullName: "BOB - Bs", currencyCode: "BOB", currencySymbol: "Bs" },
  { fullName: "BRL - R$", currencyCode: "BRL", currencySymbol: "R$" },
  { fullName: "BSD - $", currencyCode: "BSD", currencySymbol: "$" },
  { fullName: "BTN - Nu.", currencyCode: "BTN", currencySymbol: "Nu." },
  { fullName: "BWP - P", currencyCode: "BWP", currencySymbol: "P" },
  { fullName: "BYN - Br", currencyCode: "BYN", currencySymbol: "Br" },
  { fullName: "BZD - BZ$", currencyCode: "BZD", currencySymbol: "BZ$" },
  { fullName: "CAD - C$", currencyCode: "CAD", currencySymbol: "C$" },
  { fullName: "CDF - FC", currencyCode: "CDF", currencySymbol: "FC" },
  { fullName: "CHF - CHF", currencyCode: "CHF", currencySymbol: "CHF" },
  { fullName: "CLP - $", currencyCode: "CLP", currencySymbol: "$" },
  { fullName: "CNY - ¥", currencyCode: "CNY", currencySymbol: "¥" },
  { fullName: "COP - $", currencyCode: "COP", currencySymbol: "$" },
  { fullName: "CRC - ₡", currencyCode: "CRC", currencySymbol: "₡" },
  { fullName: "CUC - CUC", currencyCode: "CUC", currencySymbol: "CUC" },
  { fullName: "CUP - $MN", currencyCode: "CUP", currencySymbol: "$MN" },
  { fullName: "CVE - $", currencyCode: "CVE", currencySymbol: "$" },
  { fullName: "CZK - Kč", currencyCode: "CZK", currencySymbol: "Kč" },
  { fullName: "DJF - Fdj", currencyCode: "DJF", currencySymbol: "Fdj" },
  { fullName: "DKK - kr.", currencyCode: "DKK", currencySymbol: "kr." },
  { fullName: "DOP - RD$", currencyCode: "DOP", currencySymbol: "RD$" },
  {
    fullName: "DZD - د.ج.‏",
    currencyCode: "DZD",
    currencySymbol: "د.ج.‏",
  },
  {
    fullName: "EGP - ج.م.‏",
    currencyCode: "EGP",
    currencySymbol: "ج.م.‏",
  },
  { fullName: "ERN - Nfk", currencyCode: "ERN", currencySymbol: "Nfk" },
  { fullName: "ETB - Br", currencyCode: "ETB", currencySymbol: "Br" },
  { fullName: "FJD - $", currencyCode: "FJD", currencySymbol: "$" },
  { fullName: "GEL - ₾", currencyCode: "GEL", currencySymbol: "₾" },
  { fullName: "GHS - GH¢", currencyCode: "GHS", currencySymbol: "GH¢" },
  { fullName: "GIP - £", currencyCode: "GIP", currencySymbol: "£" },
  { fullName: "GMD - D", currencyCode: "GMD", currencySymbol: "D" },
  { fullName: "GNF - FG", currencyCode: "GNF", currencySymbol: "FG" },
  { fullName: "GTQ - Q", currencyCode: "GTQ", currencySymbol: "Q" },
  { fullName: "GYD - $", currencyCode: "GYD", currencySymbol: "$" },
  { fullName: "HKD - HK$", currencyCode: "HKD", currencySymbol: "HK$" },
  { fullName: "HNL - L.", currencyCode: "HNL", currencySymbol: "L." },
  { fullName: "HRK - kn", currencyCode: "HRK", currencySymbol: "kn" },
  { fullName: "HTG - G", currencyCode: "HTG", currencySymbol: "G" },
  { fullName: "HUF - Ft", currencyCode: "HUF", currencySymbol: "Ft" },
  { fullName: "IDR - Rp", currencyCode: "IDR", currencySymbol: "Rp" },
  { fullName: "ILS - ₪", currencyCode: "ILS", currencySymbol: "₪" },
  { fullName: "INR - ₹", currencyCode: "INR", currencySymbol: "₹" },
  {
    fullName: "IQD - د.ع.‏",
    currencyCode: "IQD",
    currencySymbol: "د.ع.‏",
  },
  { fullName: "IRR - ريال", currencyCode: "IRR", currencySymbol: "ريال" },
  { fullName: "ISK - kr.", currencyCode: "ISK", currencySymbol: "kr." },
  { fullName: "JMD - J$", currencyCode: "JMD", currencySymbol: "J$" },
  {
    fullName: "JOD - د.ا.‏",
    currencyCode: "JOD",
    currencySymbol: "د.ا.‏",
  },
  { fullName: "JPY - ¥", currencyCode: "JPY", currencySymbol: "¥" },
  { fullName: "KES - S", currencyCode: "KES", currencySymbol: "S" },
  { fullName: "KGS - сом", currencyCode: "KGS", currencySymbol: "сом" },
  { fullName: "KHR - KHR", currencyCode: "KHR", currencySymbol: "KHR" },
  { fullName: "KMF - CF", currencyCode: "KMF", currencySymbol: "CF" },
  { fullName: "KPW - ₩", currencyCode: "KPW", currencySymbol: "₩" },
  { fullName: "KRW - ₩", currencyCode: "KRW", currencySymbol: "₩" },
  {
    fullName: "KWD - د.ك.‏",
    currencyCode: "KWD",
    currencySymbol: "د.ك.‏",
  },
  { fullName: "KYD - $", currencyCode: "KYD", currencySymbol: "$" },
  { fullName: "KZT - Т", currencyCode: "KZT", currencySymbol: "Т" },
  { fullName: "LAK - ₭", currencyCode: "LAK", currencySymbol: "₭" },
  {
    fullName: "LBP - ل.ل.‏",
    currencyCode: "LBP",
    currencySymbol: "ل.ل.‏",
  },
  { fullName: "LKR - Rp", currencyCode: "LKR", currencySymbol: "Rp" },
  { fullName: "LRD - $", currencyCode: "LRD", currencySymbol: "$" },
  { fullName: "LSL - M", currencyCode: "LSL", currencySymbol: "M" },
  {
    fullName: "LYD - د.ل.‏",
    currencyCode: "LYD",
    currencySymbol: "د.ل.‏",
  },
  {
    fullName: "MAD - د.م.‏",
    currencyCode: "MAD",
    currencySymbol: "د.م.‏",
  },
  { fullName: "MDL - lei", currencyCode: "MDL", currencySymbol: "lei" },
  { fullName: "MGA - Ar", currencyCode: "MGA", currencySymbol: "Ar" },
  { fullName: "MKD - ден.", currencyCode: "MKD", currencySymbol: "ден." },
  { fullName: "MMK - K", currencyCode: "MMK", currencySymbol: "K" },
  { fullName: "MNT - ₮", currencyCode: "MNT", currencySymbol: "₮" },
  { fullName: "MOP - MOP$", currencyCode: "MOP", currencySymbol: "MOP$" },
  { fullName: "MRO - UM", currencyCode: "MRO", currencySymbol: "UM" },
  { fullName: "MUR - Rs", currencyCode: "MUR", currencySymbol: "Rs" },
  { fullName: "MVR - MVR", currencyCode: "MVR", currencySymbol: "MVR" },
  { fullName: "MWK - MK", currencyCode: "MWK", currencySymbol: "MK" },
  { fullName: "MXN - $", currencyCode: "MXN", currencySymbol: "$" },
  { fullName: "MYR - RM", currencyCode: "MYR", currencySymbol: "RM" },
  { fullName: "MZN - MT", currencyCode: "MZN", currencySymbol: "MT" },
  { fullName: "NAD - $", currencyCode: "NAD", currencySymbol: "$" },
  { fullName: "NGN - ₦", currencyCode: "NGN", currencySymbol: "₦" },
  { fullName: "NIO - C$", currencyCode: "NIO", currencySymbol: "C$" },
  { fullName: "NOK - kr", currencyCode: "NOK", currencySymbol: "kr" },
  { fullName: "NPR - रु", currencyCode: "NPR", currencySymbol: "रु" },
  { fullName: "NZD - $", currencyCode: "NZD", currencySymbol: "$" },
  {
    fullName: "OMR - ر.ع.‏",
    currencyCode: "OMR",
    currencySymbol: "ر.ع.‏",
  },
  { fullName: "PAB - B/.", currencyCode: "PAB", currencySymbol: "B/." },
  { fullName: "PEN - S/.", currencyCode: "PEN", currencySymbol: "S/." },
  { fullName: "PGK - K", currencyCode: "PGK", currencySymbol: "K" },
  { fullName: "PHP - P", currencyCode: "PHP", currencySymbol: "P" },
  { fullName: "PKR - Rs", currencyCode: "PKR", currencySymbol: "Rs" },
  { fullName: "PLN - zł", currencyCode: "PLN", currencySymbol: "zł" },
  { fullName: "PYG - Gs", currencyCode: "PYG", currencySymbol: "Gs" },
  {
    fullName: "QAR - ر.ق.‏",
    currencyCode: "QAR",
    currencySymbol: "ر.ق.‏",
  },
  { fullName: "RON - lei", currencyCode: "RON", currencySymbol: "lei" },
  { fullName: "RSD - Дин.", currencyCode: "RSD", currencySymbol: "Дин." },
  { fullName: "RUB - ₽", currencyCode: "RUB", currencySymbol: "₽" },
  { fullName: "RWF - RWF", currencyCode: "RWF", currencySymbol: "RWF" },
  { fullName: "SAR - SAR", currencyCode: "SAR", currencySymbol: "SAR" },
  { fullName: "SBD - $", currencyCode: "SBD", currencySymbol: "$" },
  { fullName: "SCR - Rs", currencyCode: "SCR", currencySymbol: "Rs" },
  {
    fullName: "SDG - ج.س.‏",
    currencyCode: "SDG",
    currencySymbol: "ج.س.‏",
  },
  { fullName: "SEK - SEK", currencyCode: "SEK", currencySymbol: "SEK" },
  { fullName: "SGD - $", currencyCode: "SGD", currencySymbol: "$" },
  { fullName: "SHP - £", currencyCode: "SHP", currencySymbol: "£" },
  { fullName: "SLL - Le", currencyCode: "SLL", currencySymbol: "Le" },
  { fullName: "SOS - S", currencyCode: "SOS", currencySymbol: "S" },
  { fullName: "SRD - $", currencyCode: "SRD", currencySymbol: "$" },
  { fullName: "STD - Db", currencyCode: "STD", currencySymbol: "Db" },
  {
    fullName: "SYP - ل.س.‏",
    currencyCode: "SYP",
    currencySymbol: "ل.س.‏",
  },
  { fullName: "SZL - E", currencyCode: "SZL", currencySymbol: "E" },
  { fullName: "THB - ฿", currencyCode: "THB", currencySymbol: "฿" },
  { fullName: "TJS - TJS", currencyCode: "TJS", currencySymbol: "TJS" },
  { fullName: "TMT - m", currencyCode: "TMT", currencySymbol: "m" },
  {
    fullName: "TND - د.ت.‏",
    currencyCode: "TND",
    currencySymbol: "د.ت.‏",
  },
  { fullName: "TOP - T$", currencyCode: "TOP", currencySymbol: "T$" },
  { fullName: "TRY - TL", currencyCode: "TRY", currencySymbol: "TL" },
  { fullName: "TTD - TT$", currencyCode: "TTD", currencySymbol: "TT$" },
  { fullName: "TWD - NT$", currencyCode: "TWD", currencySymbol: "NT$" },
  { fullName: "TZS - TSh", currencyCode: "TZS", currencySymbol: "TSh" },
  { fullName: "UAH - грн.", currencyCode: "UAH", currencySymbol: "грн." },
  { fullName: "UGX - USh", currencyCode: "UGX", currencySymbol: "USh" },
  { fullName: "UYU - $U", currencyCode: "UYU", currencySymbol: "$U" },
  { fullName: "UZS - сўм", currencyCode: "UZS", currencySymbol: "сўм" },
  { fullName: "VND - ₫", currencyCode: "VND", currencySymbol: "₫" },
  { fullName: "VUV - VT", currencyCode: "VUV", currencySymbol: "VT" },
  { fullName: "WST - WS$", currencyCode: "WST", currencySymbol: "WS$" },
  { fullName: "XAF - F", currencyCode: "XAF", currencySymbol: "F" },
  { fullName: "XCD - $", currencyCode: "XCD", currencySymbol: "$" },
  { fullName: "XOF - F", currencyCode: "XOF", currencySymbol: "F" },
  { fullName: "XPF - F", currencyCode: "XPF", currencySymbol: "F" },
  {
    fullName: "YER - ر.ي.‏",
    currencyCode: "YER",
    currencySymbol: "ر.ي.‏",
  },
  { fullName: "ZAR - R", currencyCode: "ZAR", currencySymbol: "R" },
  { fullName: "ZMW - ZK", currencyCode: "ZMW", currencySymbol: "ZK" },
];
